version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - graphql_db_data:/var/lib/mysql
      - ./myconf/my.cnf:/etc/mysql/conf.d/my.cnf
  app:
    init: true
    build:
      context: .
    volumes:
      - ./:/usr/app
    ports:
      - 8111:3000
    environment:
      DATABASE_HOST: db
    tty: true
    depends_on:
      - db
volumes:
  graphql_db_data: